linters-settings:
  lll: 
    line-length: 120
    tab-width: 2
    auto-fix: true
linters:
  enable:
    - lll
    - deadcode
    - errcheck
    - gosimple 
    - govet 
    - ineffassign
    - staticcheck 
    - structcheck
    - typecheck
    - unused 
    - varcheck