linters-settings:
  lll: 
    line-length: 128
    tab-width: 2
    autofix: true
  cyclop:
   max-complexity: 18
  funlen:
   lines: 165
   statements: 50
   ignore-blank-lines: true
   ignore-comments: true
linters:
  enable:
    - lll
    - errcheck
    - gosimple 
    - govet 
    - ineffassign
    - staticcheck 
    - typecheck
    - unused 
    - cyclop
    - funlen
    - goconst
    - gofmt
    - godox
    - misspell
    - reassign
    - whitespace