linters-settings:
  lll: 
    line-length: 128
    tab-width: 2
    autofix: true
  funlen:
   lines: 60
   statements: 50
   ignore-blank-lines: true
   ignore-comments: true
  # cyclop:
  #  max-complexity: 10
linters:
  enable:
    - lll
    - errcheck
    - gosimple 
    - govet 
    - ineffassign
    - staticcheck 
    - typecheck
    - unused 
    - funlen
    - goconst
    - gofmt
    - godox
    - misspell
    - reassign
    - whitespace