linters-settings:
  lll: 
    line-length: 128
    tab-width: 2
    autofix: true
  cyclop:
   max-complexity: 10
   skip-tests: true
  funlen:
   lines: 100
   statements: 50
   ignore-tests: true
   ignore-blank-lines: true
linters:
  enable:
    - lll
    - errcheck
    - gosimple 
    - govet 
    - ineffassign
    - staticcheck 
    - typecheck
    - unused 
    - cyclop
    - funlen
    - goconst
    - gofmt
    - godox
    - misspell
    - reassign
    - whitespace
    
issues:
  exclude-rules:
      - path: '(.+)_test\.go'
        linters:
          - funlen
          - typecheck
