version: '3.8'

services:
  server:
    stdin_open: true
    tty: true
    build:
      target: local
    env_file:
      - .env.local
    volumes:
      - type: bind
        source: .
        target: /go/src/server

  pgAdmin:
    image: dpage/pgadmin4:4
    restart: always
    depends_on:
      - db
    ports:
      - ${PGADMIN_PORT}:80
    environment:
    - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
    - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS}