version: '3.6'

services:
  db_postgres:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - '5432'
    restart: always
    env_file:
      - .env.local
  paycore_api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db_postgres
    ports:
      - "9000:9000"
    expose:
      - "9000"
    env_file:
      - .env.local
