version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    env_file:
      - .env.docker
    environment:
      - POSTGRES_USER=go_template_role
      - POSTGRES_PASSWORD=go_template_role456
      - POSTGRES_PORT=5432
      - POSTGRES_DB=go_template
    depends_on:
      - redis
    ports:
      - "5432:5432"
  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - "6379:6379"

  wait-for-db:
    image: atkrad/wait4x
    depends_on:
      - db
    command: tcp db:5432 -t 30s -i 250ms

  app:
    build: .
    restart: always
    env_file:
      - ./.env.docker
    depends_on:
      wait-for-db:
        condition: service_completed_successfully
    ports:
      - "9000:9000"
    environment:
      ENVIRONMENT_NAME: 'docker'

   