package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"fmt"
	"go-template/gqlmodels"
)

// Author is the resolver for the author field.
func (r *queryResolver) Author(ctx context.Context, id string) (*gqlmodels.Author, error) {
	panic(fmt.Errorf("not implemented: Author - author"))
}

// Authors is the resolver for the authors field.
func (r *queryResolver) Authors(ctx context.Context, pagination gqlmodels.Pagination) (*gqlmodels.AuthorsPayload, error) {
	panic(fmt.Errorf("not implemented: Authors - authors"))
}

// Query returns gqlmodels.QueryResolver implementation.
func (r *Resolver) Query() gqlmodels.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
