package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"go-template/gqlmodels"
	"go-template/post-model"
)

// CreatePost is the resolver for the create_post field.
func (r *mutationResolver) CreatePost(ctx context.Context, id int, content string) (*gqlmodels.Post, error) {
	post, err := r.PostDAO.CreatePost(model.PostModel{
		ID:      id,
		Content: content,
	})
	if err != nil {
		return nil, err
	}
	createdAt := int(post.CreatedAt.UnixNano())
	return &gqlmodels.Post{
		ID:        id,
		Content:   content,
		CreatedAt: &createdAt,
	}, nil
}
